server:
  port: 8111


spring:
  application:
    name: cisdi-info-ms-cms_sample
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/temp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    url: jdbc:mysql://192.168.20.55:3306/d4?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: abcd575351
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect           #指定数据库引擎
logging:
  file: d:/D4/DDDLog/ddd.log #日志文件输出目录
  level:
    com.cisdi.info: debug #日志Level设定
mybatis:
  mapper-locations:
  - classpath*:/com/cisdi/info/sqlMapper/**/*.xml     #mybaits mapperxml文件路径，使用了cms后不要修改或者删除
  - classpath*:/com/cisdi/info/**/dao/**/mapper/*.xml     #mybaits mapperxml文件路径
  configuration:
    map-underscore-to-camel-case: true
