server:
  port: 8111


spring:
  application:
    name: cisdi-info-ms-cms_sample
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/d4?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:3306/d4?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
        properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect #指定数据库引擎
  redis:
    host: 59.110.221.188
    port: 6379
    password: ddd306ddd
logging:
  level:
    com.cisdi.info: Debug #日志Level设定
  #file: 日志文件输出路径
mybatis:
    mapper-locations:
      - classpath*:/com/cisdi/info/sqlMapper/**/*.xml #mybaits mapperxml文件路径，使用了cms后不要修改或者删除
      - classpath*:/com/cisdi/info/**/dao/**/mapper/*.xml #mybaits mapperxml文件路径
    configuration:
        map-underscore-to-camel-case: true
cisdi:
  websecurity:
    permitAllantMachers: #此处为数组形式，配置为不受认证处理的url路径Pattern
      - /static/** #js和css相关文件
      - /cms/index.html #cms主页
      - /favicon.ico
      - /Login/**
    #loginPage: /cms/login #默认跳转登陆页面路径，因为已经前后分离不起效果，如果需要起效将redirectLogin配置为true。
    loginProcessingUrl: /Login/loginSubmit #登陆处理url，需要post形式提交，使用cms后不要更改
    logoutUrl: /cms/logout #退出处理url，需要以post方式提交。使用cms后不要更改
    rejectPublicInvocations: true #默认不配置为false，true为未设定权限资源不否允许访问
