server:
  port: 8080
spring:
  application:
    name: cisdi-info-ms-cms_ample
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/temp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    schema: classpath:/sql/quartz.sql
    initialization-mode: always
  quartz:
      #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect           #指定数据库引擎
      properties:
        hibernate:
          dialect: com.cisdi.info.simple.config.MySQL5DialectUTF8

  mvc:
    static-path-pattern: /file/**
  resources:
    static-locations: file:D://D4/DDDFile/

logging:
  config: classpath:logback.xml #日志配置

mybatis:
  mapper-locations:
  - classpath*:/com/cisdi/info/sqlMapper/**/*.xml     #mybaits mapperxml文件路径，使用了cms后不要修改或者删除
  - classpath*:/com/cisdi/info/**/dao/**/mapper/*.xml     #mybaits mapperxml文件路径
  configuration:
    map-underscore-to-camel-case: true

