server:
  port: 8080


spring:
  application:
    name: D4-info-ms-cms_ample
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/d4?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
        properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect #指定数据库引擎
    properties:
         hibernate:
                dialect: com.cisdi.info.simple.config.MySQL5DialectUTF8

  mvc:
    static-path-pattern: /file/**
  resources:
    static-locations: file:D://D4/DDDFile/

logging:
  file: d:/D4/DDDLog/ddd.log #日志文件输出目录
  level:
    com.cisdi.info: debug #日志Level设定

mybatis:
    mapper-locations:
      - classpath*:/com/cisdi/info/sqlMapper/**/*.xml #mybaits mapperxml文件路径，使用了cms后不要修改或者删除
      - classpath*:/com/cisdi/info/**/dao/**/mapper/*.xml #mybaits mapperxml文件路径
    configuration:
        map-underscore-to-camel-case: true
