simple:
  workspapce: E:\\SpringBoot\\workplace
  serverPath: ${workspapce}\\D4\\simple
  uiPath: ${workspapce}\\D4_pc_ui
  codeTablesFile: ${serverPath}\\src\\main\\resources\\codetables.json
  moduleFile: ${serverPath}\\src\\main\\resources\\modules.json
  velocityTemplate: ${workspapce}\\D4\\generator\\src\\main\\resources
  exceptionLogPath: D:\\D4\\DDDException
  uploadFileAddress: D:\\D4\\spring_files
  staticFilePath: D:\\D4\\DDDFile\\
  logPath: D:\\D4\\DDDException\\

  applicationName: d4Frame
  applicationCode: DDD4
  shortCode: DD
  basePackage: com.cisdi.info
  src: src\\
  charset_UTF8: UTF-8
  charset_ISO: ISO-8859-1
  dataBase: mysql
  serverId: app1
  isDeveloping: true
  whiteURLs: /Captcha/hasVertify,/Login/logout,/Login/getOrganizations,/Login/sendEmailCode,/Login/saveAttachment,/Login/findOrganizationsWithIdNameByName,/Login/saveEmployeRegist,/Login/saveOrganizationRegist,/Login/qingtuiInit,/Login/bindingQingtui,/Login/constructNewTree,/Login/loginSubmit,/Login/wisdomCateringLoginSubmit,/Login/wisdomCateringConstructNewTree,/Login/wisdomCateringLogout,/generator/generateModel,/generator/createSuperOperator,/generator/generateMethod,/generator/generateBaseCode,/error,/generator/testException,/Login/phoneLoginSubmit,/Login/test,/simple/fileUpload/addFile,/simple/excel/excelExport,/simple/excel/excelExportAll,/simple/word/wordExport,/simple/excel/excelImport,/simple/word/wordTemplate,/Captcha/getCaptcha,/Captcha/hasVertify,/simple/attachment/Attachment/download,simple/password

